non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика. # незавершенность требования. 
  - Сайт должен быть доступен на различных устройствах. # незавершенность требования. 
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. # незавершенность требования. 
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
implicit:
 - Сайт нужно протестировать на локализацию текста. # например наличие текста, грамматика. 
 - Сайт нужно протестировать на локализацию функционала. # валюта, единицы измерения. 
 # В целом можно обозначить множество неявных требований, но в рамках этого тестирования и проекта не хотелось бы конкретно на этом делать упор. 
 # Ибо еще по всем ним же тест кейсы делать. 
 
