# На мой взгляд некоторые требования не соответствуют определенным характеристикам. 
# Не соблюдается атомарность, Завершённость, где-то не хватает ясности, единичности. 
# Из-за этого в дальнейшем возникает куча вопросов и несостыковок при работе с такими требованиями. 
# Но работаем с тем, что имеем и адаптируемся под ситуацию :) 
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика. 
  - Сайт должен быть доступен на различных устройствах. 
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. 
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
implicit:
 - Сайт нужно протестировать на локализацию текста в описании товаров.
 - Сайт нужно протестировать на локализацию текста в разделе Категория. 
 - Пользователь должен иметь возможность оформлять заказ. #добавил после первой проверки
 - Пользователь должен иметь возможность очищать корзину. #добавил после первой проверки
 - Пользователь должен иметь возможность добавлять несколько товаров в корзину. #добавил после первой проверки
 - Пользователь должен иметь возможность переключать язык. #добавил после первой проверки
 - Пользователь должен иметь возможность переходить из товара в категорию товаров по хештегу. #добавил после первой проверки

# Заранее хочу отметить тот факт, что некоторые требования можно понять неоднозначно,
# и мои тест кейсы были реализованы с учетом моего понимания требования, прошу это учесть при проверке, буду рад фитбеку, 
# если что-то реализовано не совсем так, как предполагалось “Аналитиком” 😊 
 
